# Generated by Django 5.0.3 on 2025-03-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_price_orderitem_unit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='order_price',
            field=models.IntegerField(default=False),
        ),
    ]
