# Generated by Django 5.0.3 on 2025-02-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on delivery'), ('Esewa', 'Esewa'), ('Stripe', 'Stripe')], max_length=100),
        ),
    ]
